FROM jupyter/minimal-notebook

LABEL maintainer="tarsnake@users.noreply.github.com"

# install typical stack
RUN conda install numpy
RUN conda install pandas
RUN conda install scipy
RUN conda install matplotlib
RUN conda install seaborn
RUN conda install ipywidgets

# install the notebook extensions and themes
RUN conda install -c conda-forge jupyter_contrib_nbextensions
RUN conda install -c conda-forge jupyterthemes