FROM jupyter/minimal-notebook

LABEL maintainer="tarsnake@users.noreply.github.com"

# install typical stack
RUN conda install numpy
RUN conda install pandas
RUN conda install scipy
RUN conda install matplotlib
RUN conda install seaborn
RUN conda install ipywidgets
RUN conda install jupyterthemes
RUN conda install jupyter_contrib_nbextensions


# install the notebook extensions
RUN conda install -c conda-forge jupyter_contrib_nbextensions